### ISSUE TITLE
Can I create my own color pattern?

### ISSUE THREAD

**Issue by MMriran** [nanxstats/ggsci#10]
Hi， thank you for your great tool! It is very useful for us to draw a beautiful picture. And I have a question about can I create my own color pattern？ For example, if I want use some colors from nejm and some colors from， and combine these colors into a scale_color_xx pattern. Then, I can use scale_color_XX to draw my picture?

**Comment by nanxstats** [comment]
Yes, you can call `ggsci::pal_nejm()(8)` to extract the color values in hex and then create your color scale functions.

**Comment by MMriran** [comment]
thank you for your reply！！！ Is there any codes that I can use to create my own color scale functions？

**Comment by nanxstats** [comment]
The blog post from Simon Jackson might help: https://drsimonj.svbtle.com/creating-corporate-colour-palettes-for-ggplot2
