### ISSUE TITLE
Manually re-order palette

### ISSUE THREAD

**Issue by flottsam** [nanxstats/ggsci#22]
This is a feature request. 
Is it possible to manually re-order the color palettes? 
For example, I would like the colors of `scale_color_tron` to be red, yellow, blue, green.. 
Great package, BTW.

**Comment by nanxstats** [comment]
@flottsam Excellent question, please see the new section in the FAQ vignette for a generic solution: https://nanx.me/ggsci/articles/ggsci-faq.html#customize-color-ordering-in-a-palette

**Comment by wook2014** [comment]
I have tried with function `scale_color_custom` to make my custom color palette but an error reported: `could not find function "scale_color_custom"`. I am using ggsci version 3.0.0. Is there any idea how the problem occurs?
