### ISSUE TITLE
Color displays priority

### ISSUE THREAD

**Issue by RuilanXu** [nanxstats/ggsci#54]
When I draw point and line plot and two groups overlap, I can not control which color to show on the top even though I have defined the order of the groups.
![example](https://github.com/user-attachments/assets/2c94d15e-c936-40b4-90f3-145e2e0646bb)

**Comment by nanxstats** [comment]
You can get ggplot2 help from <https://ggplot2.tidyverse.org/#getting-help>.

**Comment by RuilanXu** [comment]
Thank you for your reply, I tried other palettes as well, and same problem appeared. I think it is the conflict with color order of the palette and the default order of the color code, never mind.
