### ISSUE TITLE
scale_color_cosmic() function didn't work

### ISSUE THREAD

**Issue by Wellington9023** [nanxstats/ggsci#9]
Error in scale_color_cosmic("hallmarks_light") : 
  could not find function "scale_color_cosmic"

**Comment by nanxstats** [comment]
It's not in the CRAN version yet. Try the development version:

```r
remotes::install_github("nanxstats/ggsci")
```

**Comment by Wellington9023** [comment]
Thanks for reply!
I used this code showing Error

> remotes::install_github("nanxstats/ggsci")
Downloading GitHub repo nanxstats/ggsci@master
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/nanxstats/ggsci/tarball/master'

and then I tried this,it seemed to work
>options(download.file.method = "libcurl")
>devtools::install_github("nanxstats/ggsci")

**Comment by nanxstats** [comment]
Glad to see it resolved.

That seems to be a wget/network issue, linking a relevant issue here: https://github.com/r-lib/remotes/issues/130.
